/**
 * Frontend-only India location constants for Region → State → City selection.
 * No backend dependency — works fully offline.
 */

export const INDIA_LOCATIONS = {
  "Andaman & Nicobar Islands": [
    "Aberdeen", "Aerial Bay", "Arong", "Bakultala", "Bamboo Flat", "Baratang", "Beodnabad", "Betapur",
    "Bharatpur", "Billiground", "Campbell Bay", "Car Nicobar", "Chatham", "Chouldari", "Chuckchucha", "Delanipur",
    "Diglipur", "Ferrargunj", "Gandhi Nagar", "Garacharma", "Govind Nagar", "Great Nicobar", "Guptapara", "Haddo",
    "Havelock Island", "Hopetown", "Hut Bay", "Indira Point", "Jirkatang", "Junglighat", "Kadamtala", "Kalipur",
    "Kinyuka", "Kishorinagar", "Laxmanpur", "Laxmi Nagar", "Laxmipur", "Little Andaman", "Long Island", "Madhupur",
    "Malacca", "Manjeri", "Mannarghat", "Mayabunder", "Middle Strait", "Mus", "Nabagram", "Neil Island",
    "Netaji Nagar", "Nilambur", "Nimbutala", "North Passage", "Pahalgaon", "Panchawati", "Perka", "Phoenix Bay",
    "Port Blair", "Prothrapur", "Rabindra Nagar", "Radhanagar", "Radhanagar Beach", "Ramakrishnapur", "Ramnagar", "Rangat",
    "Ross Island", "Sawai", "Shastri Nagar", "Shoal Bay", "Shyam Nagar", "Sippighat", "Sita Nagar", "Sitapur",
    "Smith Island", "Stewart Island", "Swadesh Nagar", "Tamul", "Tee Top", "Tugapur", "Tushnabad", "Vijay Nagar",
    "Vijaynagar", "Vivekanandapuram", "Wandoor", "Wimberlygunj"
  ],
  "Andhra Pradesh": [
    "Addanki", "Adoni", "Allagadda", "Amalapuram", "Amudalavalasa", "Anakapalle", "Anantapur", "Atmakur",
    "Banaganapalle", "Bapatla", "Bhimavaram", "Bobbili", "Chilakaluripet", "Chirala", "Chittoor", "Dharmavaram",
    "Dhone", "Eluru", "Giddalur", "Gudivada", "Gudur", "Guntakal", "Guntur", "Hindupur",
    "Ichchapuram", "Jammalamadugu", "Kadapa", "Kadiri", "Kakinada", "Kalyandurg", "Kandukur", "Kanigiri",
    "Kavali", "Kuppam", "Kurnool", "Macherla", "Machilipatnam", "Madakasira", "Madanapalle", "Mangalagiri",
    "Markapur", "Nagari", "Naidupeta", "Nandikotkur", "Nandyal", "Narasapuram", "Narasaraopet", "Narsipatnam",
    "Nellore", "Nuzvid", "Ongole", "Palakollu", "Palamaner", "Palasa", "Parvathipuram", "Peddapuram",
    "Penukonda", "Pileru", "Pithapuram", "Ponnur", "Proddatur", "Punganur", "Puttur", "Rajahmundry",
    "Rayachoti", "Rayadurg", "Renigunta", "Repalle", "Salur", "Samalkot", "Sattenapalle", "Singarayakonda",
    "Srikakulam", "Srikalahasti", "Sullurpeta", "Tadepalligudem", "Tadipatri", "Tanuku", "Tekkali", "Tenali",
    "Tirupati", "Tuni", "Uravakonda", "Vayalpad", "Venkatagiri", "Vijayawada", "Vinukonda", "Visakhapatnam",
    "Vizianagaram", "Yemmiganur"
  ],
  "Arunachal Pradesh": [
    "Aalo", "Along", "Anelih", "Anini", "Basar", "Bhalukpong", "Boleng", "Bomdila",
    "Bordumsa", "Changlang", "Daporijo", "Deomali", "Dirang", "Dumporijo", "Etalin", "Geku",
    "Gelling", "Gensi", "Hawai", "Hayuliang", "Itanagar", "Jairampur", "Jang", "Kalaktang",
    "Kanubari", "Kaying", "Khonsa", "Kibithoo", "Koloriang", "Kra Daadi", "Likabali", "Longding",
    "Lumla", "Mariyang", "Mechuka", "Miao", "Naharlagun", "Namsai", "Nari", "Nyapin",
    "Palin", "Pangin", "Pasighat", "Pipsorang", "Riga", "Roing", "Rumgong", "Rupa",
    "Sangram", "Seijosa", "Seppa", "Singa", "Tali", "Taliha", "Tawang", "Tezu",
    "Tuting", "Walong", "Yingkiong", "Ziro"
  ],
  "Assam": [
    "Abhayapuri", "Algapur", "Amguri", "Badarpur", "Baghbor", "Baksa", "Barpeta", "Barpeta Road",
    "Basugaon", "Bihpuria", "Bijni", "Bilasipara", "Biswanath Chariali", "Bokajan", "Bokakhat", "Bongaigaon",
    "Chabua", "Chirang", "Dalgaon", "Dergaon", "Dhakuakhana", "Dhekiajuli", "Dhemaji", "Dhubri",
    "Dibrugarh", "Digboi", "Diphu", "Doboka", "Doom Dooma", "Duliajan", "Goalpara", "Gogamukh",
    "Gohpur", "Golaghat", "Gossaigaon", "Guwahati", "Haflong", "Hailakandi", "Hamren", "Hojai",
    "Howraghat", "Jagiroad", "Jaleswar", "Jamugurihat", "Jonai", "Jorhat", "Kalaigaon", "Kamrup",
    "Karimganj", "Katigorah", "Kharupetia", "Kokrajhar", "Lakhipur", "Lala", "Lanka", "Lumding",
    "Majuli", "Makum", "Mangaldoi", "Margherita", "Mariani", "Moran", "Morigaon", "Nagaon",
    "Naharkatia", "Nakachari", "Nalbari", "Namrup", "Narayanpur", "Nazira", "North Lakhimpur", "Numaligarh",
    "Paneri", "Patharkandi", "Pathsala", "Ramkrishna Nagar", "Rangapara", "Rangia", "Sarthebari", "Silapathar",
    "Silchar", "Simaluguri", "Sivasagar", "Sonari", "Tangla", "Tezpur", "Tinsukia", "Titabor",
    "Udalguri"
  ],
  "Bihar": [
    "Amarpur", "Araria", "Arrah", "Arwal", "Aurangabad", "Bagra", "Bahadurganj", "Bairgania",
    "Bakhtiarpur", "Banka", "Banmankhi", "Barauni", "Barh", "Begusarai", "Benipur", "Bettiah",
    "Bhabua", "Bhagalpur", "Bihar Sharif", "Birpur", "Bodh Gaya", "Buxar", "Chakia", "Chapra",
    "Dalsinghsarai", "Danapur", "Darbhanga", "Dehri", "Dhamdaha", "Dumraon", "Forbesganj", "Gaya",
    "Gogri", "Gopalganj", "Hajipur", "Hilsa", "Jagdishpur", "Jainagar", "Jamalpur", "Jamui",
    "Jehanabad", "Jhanjharpur", "Jogbani", "Kahalgaon", "Katihar", "Khagaria", "Khagaul", "Kishanganj",
    "Koilwar", "Lakhisarai", "Madhepura", "Madhubani", "Maharajganj", "Marhaura", "Masaurhi", "Mirganj",
    "Mokama", "Motihari", "Munger", "Murliganj", "Muzaffarpur", "Nalanda", "Narkatiaganj", "Naugachia",
    "Nawada", "Nirmali", "Pakridayal", "Patna", "Phulparas", "Phulwari Sharif", "Piro", "Pupri",
    "Purnia", "Rajgir", "Raxaul", "Revelganj", "Rosera", "Runnisaidpur", "Saharsa", "Samastipur",
    "Sasaram", "Sheikhpura", "Sheohar", "Sherghati", "Simri Bakhtiarpur", "Sitamarhi", "Siwan", "Sultanganj",
    "Supaul", "Teghra", "Tekari", "Thakurganj", "Warisaliganj"
  ],
  "Chandigarh": [
    "Attawa", "Behlana", "Burail", "Chandigarh", "Dadu Majra", "Daria", "Hallomajra", "Industrial Area",
    "Kajheri", "Kishangarh", "Maloya", "Manimajra", "Palsora", "Raipur Kalan", "Raipur Khurd", "Sector 1",
    "Sector 10", "Sector 11", "Sector 12", "Sector 14", "Sector 15", "Sector 16", "Sector 17", "Sector 18",
    "Sector 19", "Sector 2", "Sector 20", "Sector 21", "Sector 22", "Sector 23", "Sector 24", "Sector 25",
    "Sector 26", "Sector 27", "Sector 28", "Sector 29", "Sector 3", "Sector 30", "Sector 31", "Sector 32",
    "Sector 33", "Sector 34", "Sector 35", "Sector 36", "Sector 37", "Sector 38", "Sector 39", "Sector 4",
    "Sector 40", "Sector 41", "Sector 42", "Sector 43", "Sector 44", "Sector 45", "Sector 46", "Sector 47",
    "Sector 48", "Sector 49", "Sector 5", "Sector 50", "Sector 6", "Sector 61", "Sector 63", "Sector 7",
    "Sector 8", "Sector 9"
  ],
  "Chhattisgarh": [
    "Abhanpur", "Akaltara", "Ambikapur", "Antagarh", "Arang", "Bagbahera", "Baikunthpur", "Balod",
    "Baloda Bazar", "Balrampur", "Basna", "Bastar", "Bemetara", "Bhanupratappur", "Bhatapara", "Bhatgaon",
    "Bhilai", "Bhopalpattnam", "Bijapur", "Bilaspur", "Champa", "Chhuikhadan", "Chhura", "Dabhra",
    "Dalli Rajhara", "Dantewada", "Deobhog", "Dhamtari", "Dharamjaigarh", "Dongargaon", "Dongargarh", "Durg",
    "Farasgaon", "Gariaband", "Gaurela", "Gharghoda", "Gunderdehi", "Gurur", "Jagdalpur", "Janjgir",
    "Jashpur", "Jashpurnagar", "Kanker", "Kasdol", "Kawardha", "Keskal", "Khairagarh", "Kharsia",
    "Kondagaon", "Konta", "Korba", "Korea", "Kota", "Kunkuri", "Kurud", "Lailunga",
    "Lundra", "Magarlod", "Mahasamund", "Mainpur", "Makdi", "Manendragarh", "Manpur", "Marwahi",
    "Mohla", "Mungeli", "Nagri", "Naila", "Narayanpur", "Pakhanjur", "Palari", "Pamgarh",
    "Patan", "Pathalgaon", "Pendra", "Pithora", "Pratappur", "Raigarh", "Raipur", "Rajim",
    "Rajnandgaon", "Ramanujganj", "Sakti", "Saraipali", "Sarangarh", "Simga", "Sitapur", "Sukma",
    "Surajpur", "Surguja", "Takhatpur", "Tamnar", "Tilda", "Wadrafnagar"
  ],
  "Dadra & Nagar Haveli and Daman & Diu": [
    "Amboli", "Amli", "Athola", "Baldevi", "Bhimpore", "Bindrabin", "Bucharwada", "Chakratirth Beach",
    "Chikhli", "Dabhel", "Dadra", "Daman", "Dapada", "Devka", "Diu", "Diu Fort",
    "Dolara", "Dudhani", "Dunetha", "Fudam", "Galonda", "Ghoghla", "Gomtimata", "Gomtimata Beach",
    "INS Khukri Memorial", "Jalandhar Beach", "Jampore", "Kachigam", "Kadaiya", "Kala", "Kanadi", "Kauncha",
    "Khadoli", "Khanvel", "Kherdi", "Luhari", "Magarvadi", "Magarwada", "Mandoni", "Marwad",
    "Masat", "Morkhal", "Moti Daman", "Nagoa", "Nagoa Beach", "Nani Daman", "Naroli", "Panikota Fort",
    "Pariyari", "Piparia", "Rakholi", "Randha", "Ringanwada", "Rudana", "Saily", "Samarvarni",
    "Silvassa", "Simbor", "Sindoni", "St. Paul Church", "Tokarkhada", "Vanakbara", "Vapi Road", "Varkund",
    "Velugam"
  ],
  "Delhi": [
    "Adarsh Nagar", "AIIMS", "Alipur", "Anand Vihar", "Ashok Vihar", "Azadpur", "Badarpur", "Badli",
    "Bawana", "Bhajanpura", "Central Delhi", "Chanakyapuri", "Chandni Chowk", "Chhattarpur", "Civil Lines", "Connaught Place",
    "Defence Colony", "Dilshad Garden", "Dwarka", "East Delhi", "Friends Colony", "Gandhi Nagar", "Geeta Colony", "Govindpuri",
    "Greater Kailash", "Green Park", "Gulabi Bagh", "Hauz Khas", "INA", "India Gate", "ITO", "Janakpuri",
    "Jangpura", "Jasola", "Kalkaji", "Kanjhawala", "Karol Bagh", "Kashmere Gate", "Keshav Puram", "Khan Market",
    "Krishna Nagar", "Lajpat Nagar", "Laxmi Nagar", "Lodi Road", "Maharani Bagh", "Mahipalpur", "Malviya Nagar", "Mandi House",
    "Mayur Vihar", "Mehrauli", "Model Town", "Mundka", "Najafgarh", "Nand Nagri", "Nangloi", "Narela",
    "Nehru Place", "New Delhi", "Nizamuddin", "North Delhi", "North East Delhi", "North West Delhi", "Okhla", "Palam",
    "Parliament Street", "Paschim Vihar", "Patparganj", "Pitampura", "Pragati Maidan", "Preet Vihar", "Punjabi Bagh", "Raisina Hill",
    "Rajghat", "Rajouri Garden", "RK Puram", "Rohini", "Saket", "Sangam Vihar", "Sarita Vihar", "Sarojini Nagar",
    "Seelampur", "Shahdara", "Shalimar Bagh", "Shastri Nagar", "Shastri Park", "South Delhi", "South East Delhi", "South Extension",
    "South West Delhi", "Tilak Nagar", "Tri Nagar", "Tughlakabad", "Uttam Nagar", "Vasant Kunj", "Vasant Vihar", "Wazirpur",
    "Welcome", "West Delhi", "Yamuna Vihar"
  ],
  "Goa": [
    "Aldona", "Anjuna", "Arambol", "Assagao", "Benaulim", "Betul", "Bicholim", "Calangute",
    "Canacona", "Candolim", "Cavelossim", "Chaudi", "Colva", "Cortalim", "Cuncolim", "Curchorem",
    "Curtorim", "Dabolim", "Dona Paula", "Fatorda", "Loutolim", "Mandrem", "Mapusa", "Marcaim",
    "Margao", "Moira", "Morjim", "Navelim", "Nerul", "Old Goa", "Pale", "Panaji",
    "Pernem", "Ponda", "Porvorim", "Quepem", "Raia", "Saligao", "Sanguem", "Sanquelim",
    "Shiroda", "Siolim", "Taleigao", "Tivim", "Usgao", "Valpoi", "Varca", "Vasco da Gama",
    "Xeldem", "Zuarinagar"
  ],
  "Gujarat": [
    "Abdasa", "Ahmedabad", "Amod", "Amreli", "Anand", "Anjar", "Ankleshwar", "Balasinor",
    "Bardoli", "Bavla", "Bayad", "Bhachau", "Bharuch", "Bhavnagar", "Bhiloda", "Bhuj",
    "Bilimora", "Borsad", "Botad", "Chhota Udepur", "Chikhli", "Chotila", "Dabhoi", "Dahej",
    "Dahod", "Deesa", "Desar", "Dhandhuka", "Dhanera", "Dhansura", "Dharampur", "Dholka",
    "Dhoraji", "Dhrangadhra", "Gandevi", "Gandhidham", "Gandhinagar", "Godhra", "Gondal", "Halol",
    "Halvad", "Himmatnagar", "Idar", "Jambughoda", "Jambusar", "Jamnagar", "Jetpur", "Junagadh",
    "Kadana", "Kadi", "Kalol", "Kapadvanj", "Kaprada", "Karjan", "Kavant", "Keshod",
    "Khambhat", "Khedbrahma", "Kheralu", "Kodinar", "Lakhpat", "Limbdi", "Lunawada", "Mahudha",
    "Mahuva", "Malpur", "Manavadar", "Mandal", "Mandvi", "Mangrol", "Meghraj", "Mehsana",
    "Modasa", "Morbi", "Mundra", "Nadiad", "Nakhatrana", "Naliya", "Naswadi", "Navsari",
    "Olpad", "Padra", "Palanpur", "Palej", "Palitana", "Pardi", "Patan", "Petlad",
    "Porbandar", "Prantij", "Radhanpur", "Rajkot", "Rajpipla", "Rapar", "Sanand", "Sankheda",
    "Santalpur", "Santrampur", "Savli", "Sidhpur", "Sihor", "Sinor", "Sojitra", "Suigam",
    "Surat", "Surendranagar", "Talaja", "Talod", "Tarapur", "Than", "Tharad", "Thasra",
    "Umbergaon", "Umreth", "Una", "Unjha", "Upleta", "Vadnagar", "Vadodara", "Vaghodia",
    "Valsad", "Vapi", "Vav", "Veraval", "Vijaynagar", "Viramgam", "Visnagar", "Vyara",
    "Wankaner"
  ],
  "Haryana": [
    "Adampur", "Ambala", "Ambala Cantt", "Assandh", "Bahadurgarh", "Barara", "Barwala", "Bawal",
    "Beri", "Bhiwani", "Bhuna", "Bilaspur", "Charkhi Dadri", "Cheeka", "Chhachhrauli", "Dabwali",
    "Dharuhera", "Ellenabad", "Faridabad", "Fatehabad", "Ferozepur Jhirka", "Ganaur", "Gharaunda", "Gohana",
    "Guhla", "Gurugram", "Hansi", "Hassanpur", "Hathin", "Hisar", "Hodal", "Indri",
    "Israna", "Jagadhri", "Jakhal", "Jhajjar", "Jind", "Julana", "Kaithal", "Kalanaur",
    "Kalanwali", "Kalayat", "Kalka", "Karnal", "Kharkhoda", "Kosli", "Kundli", "Kurukshetra",
    "Ladwa", "Loharu", "Madlauda", "Mahendragarh", "Matanhail", "Meham", "Mullana", "Mustafabad",
    "Nagina", "Naraingarh", "Narnaul", "Narnaund", "Narwana", "Nilokheri", "Nissing", "Nuh",
    "Odhan", "Palwal", "Panchkula", "Panipat", "Pataudi", "Pehowa", "Pinjore", "Punahana",
    "Pundri", "Radaur", "Rai", "Raipur Rani", "Rania", "Ratia", "Rewari", "Rohtak",
    "Sadhaura", "Safidon", "Salhawas", "Samalkha", "Sampla", "Shahbad", "Sirsa", "Siwani",
    "Sohna", "Sonipat", "Taoru", "Taraori", "Thanesar", "Tohana", "Tosham", "Uchana",
    "Uklana", "Yamunanagar"
  ],
  "Himachal Pradesh": [
    "Amb", "Anni", "Arki", "Aut", "Baddi", "Baijnath", "Bali Chowki", "Bangana",
    "Banjar", "Barsar", "Bharmour", "Bhoranj", "Bhuntar", "Bilaspur", "Chamba", "Chopal",
    "Churah", "Dadasiba", "Dalhousie", "Daulatpur", "Dehra", "Dharamshala", "Fatehpur", "Gagret",
    "Ghumarwin", "Hamirpur", "Haroli", "Indora", "Jawalamukhi", "Jawali", "Jhandutta", "Jogindernagar",
    "Jubbal", "Kandaghat", "Kangra", "Karsog", "Kasauli", "Kaza", "Keylong", "Kinnaur",
    "Kotkhai", "Kullu", "Kumarsain", "Manali", "Mandi", "Manikaran", "McLeod Ganj", "Nadaun",
    "Naggar", "Nahan", "Nalagarh", "Narkanda", "Nirmand", "Nurpur", "Palampur", "Pandoh",
    "Pangi", "Paonta Sahib", "Parwanoo", "Rajgarh", "Rampur", "Reckong Peo", "Renuka", "Rohru",
    "Salooni", "Sangrah", "Sarkaghat", "Seraj", "Shahpur", "Shillai", "Shimla", "Solan",
    "Spiti", "Sujanpur", "Sundernagar", "Theog", "Tira Sujanpur", "Una"
  ],
  "Jammu & Kashmir": [
    "Achabal", "Akhnoor", "Anantnag", "Arnas", "Arnia", "Atholi", "Awantipora", "Bahu",
    "Balakote", "Bandipora", "Bani", "Banihal", "Baramulla", "Basholi", "Batote", "Beerwah",
    "Bhaderwah", "Bijbehara", "Billawar", "Bishnah", "Boniyar", "Budgam", "Budhal", "Chadoora",
    "Chatroo", "Chenani", "Dangerpora", "Dansal", "Darhal", "Devsar", "Doda", "Dooru",
    "Frisal", "Ganderbal", "Gandhinagar", "Gandoh", "Ghagwal", "Gool", "Gulmarg", "Gurez",
    "Hajin", "Handwara", "Hiranagar", "Imamsahib", "Jammu", "Kakapora", "Kalakote", "Kangan",
    "Karnah", "Kathua", "Katra", "Keller", "Khan Sahib", "Kishtwar", "Kokernag", "Kreeri",
    "Kulgam", "Kupwara", "Lakhanpur", "Langate", "Lar", "Litter", "Magam", "Mahore",
    "Mandi", "Marh", "Marwah", "Mendhar", "Nagrota", "Narbal", "Nowshera", "Paddar",
    "Pahalgam", "Pampore", "Pattan", "Poonch", "Pouni", "Pulwama", "Purmandal", "Qaimoh",
    "Qazigund", "Rajouri", "Ramban", "Ramgarh", "Ramnagar", "Ramsoo", "Reasi", "Rohama",
    "RS Pura", "Safapora", "Samba", "Satwari", "Shangus", "Shopian", "Sogam", "Sopore",
    "Srinagar", "Suchetgarh", "Sumbal", "Sunderbani", "Surankote", "Tangdhar", "Tangmarg", "Thanamandi",
    "Thathri", "Tral", "Trehgam", "Tulail", "Udhampur", "Uri", "Verinag", "Vijaypur",
    "Wakoora", "Warwan", "Watergam", "Yaripora", "Zainapora"
  ],
  "Jharkhand": [
    "Adityapur", "Amrapara", "Angara", "Bagodar", "Barajamda", "Barharwa", "Barhi", "Barkagaon",
    "Barkatha", "Bengabad", "Bero", "Bokaro", "Borio", "Bundu", "Burmu", "Chaibasa",
    "Chakradharpur", "Chalkusa", "Chandil", "Chanho", "Chatra", "Chiria", "Churchu", "Deoghar",
    "Devipur", "Dhanbad", "Dhanwar", "Dumka", "Fatehpur", "Gamharia", "Garhwa", "Gawan",
    "Ghatshila", "Giridih", "Godda", "Gola", "Gopikandar", "Gua", "Gumla", "Hazaribagh",
    "Hiranpur", "Ichak", "Itki", "Jama", "Jamshedpur", "Jamtara", "Jamua", "Jasidih",
    "Jugsalai", "Kanke", "Karon", "Kathikund", "Khunti", "Kiriburu", "Koderma", "Kundahit",
    "Latehar", "Littipara", "Lohardaga", "Madhupur", "Maheshpur", "Mandar", "Mandro", "Mango",
    "Manoharpur", "Masalia", "Medininagar", "Mohanpur", "Musabani", "Nagri", "Nala", "Namkum",
    "Narayanpur", "Noamundi", "Ormanjhi", "Padma", "Pakur", "Pakuria", "Palamu", "Palojori",
    "Pathna", "Patratu", "Phusro", "Pirtand", "Rajmahal", "Ramgarh", "Ranchi", "Ranishwar",
    "Ratu", "Sahebganj", "Saraikela", "Sarath", "Sarwan", "Shikaripara", "Silli", "Simdega",
    "Sonahatu", "Taljhari", "Tamar", "Tati", "Tati Jhariya", "Tisri", "Udhwa"
  ],
  "Karnataka": [
    "Afzalpur", "Aland", "Alur", "Arkalgud", "Arsikere", "Athani", "Aurad", "Badami",
    "Bagalkot", "Bagepalli", "Bailhongal", "Ballari", "Bangarapet", "Bantwal", "Basavakalyan", "Belagavi",
    "Belur", "Bengaluru", "Bhadravati", "Bhalki", "Bidadi", "Bidar", "Bilagi", "Chamarajanagar",
    "Channagiri", "Channapatna", "Channarayapatna", "Chikkaballapur", "Chikkamagaluru", "Chiknayakanhalli", "Chikodi", "Chincholi",
    "Chintamani", "Chitradurga", "Chittapur", "Davangere", "Devadurga", "Dharwad", "Gadag", "Gauribidanur",
    "Gokak", "Gubbi", "Gudibanda", "Guledgudda", "Gundlupet", "Hanur", "Harapanahalli", "Harihara",
    "Harohalli", "Hassan", "Haveri", "Heggadadevanakote", "Hole Narsipur", "Honnali", "Hosanagara", "Hospet",
    "Hubballi", "Hukkeri", "Humnabad", "Hungund", "Hunsur", "Ilkal", "Jagalur", "Jamkhandi",
    "Jevargi", "Kadur", "Kalaburagi", "Kanakapura", "Karkala", "Karwar", "KGF", "Khanapur",
    "Kodagu", "Kolar", "Kollegal", "Koppa", "Koppal", "Koratagere", "Krishnarajanagara", "Krishnarajapet",
    "Kudligi", "Kundapura", "Kunigal", "Lingsugur", "Madapura", "Maddur", "Madhugiri", "Madikeri",
    "Magadi", "Malavalli", "Malur", "Mandya", "Mangaluru", "Manvi", "Moodbidri", "Mudhol",
    "Mudigere", "Mulbagal", "Mysuru", "N.R. Pura", "Nagamangala", "Nanjangud", "Nippani", "Pandavapura",
    "Pavagada", "Piriyapatna", "Puttur", "Rabkavi Banhatti", "Raibag", "Raichur", "Ramanagara", "Ramdurg",
    "Robertsonpet", "Sagara", "Sakleshpur", "Sandur", "Savadatti", "Sedam", "Shahapur", "Shikaripur",
    "Shivamogga", "Shorapur", "Sidlaghatta", "Sindhanur", "Sira", "Sirsi", "Siruguppa", "Somwarpet",
    "Sorab", "Sringeri", "Srinivaspur", "Srirangapatna", "Sullia", "T. Narasipur", "Tarikere", "Terdal",
    "Tiptur", "Tirthahalli", "Tumakuru", "Turuvekere", "Udupi", "Vijayapura", "Virajpet", "Yadgir",
    "Yelandur"
  ],
  "Kerala": [
    "Adoor", "Alappuzha", "Alathur", "Aluva", "Angamaly", "Attingal", "Beypore", "Chalakudy",
    "Changanassery", "Chavakkad", "Chengannur", "Cherai", "Cherthala", "Chittur", "Ernakulam", "Ettumanoor",
    "Feroke", "Fort Kochi", "Guruvayur", "Haripad", "Idukki", "Irinjalakuda", "Kalamassery", "Kalpetta",
    "Kanhangad", "Kanjirappally", "Kannur", "Karunagappally", "Kasaragod", "Kattappana", "Kayamkulam", "Kochi",
    "Kodungallur", "Kollam", "Kondotty", "Konni", "Kothamangalam", "Kottakkal", "Kottarakkara", "Kottayam",
    "Koyilandy", "Kozhikode", "Kumily", "Kunnamkulam", "Malappuram", "Mananthavady", "Manjeri", "Mannarkkad",
    "Mattancherry", "Mavelikkara", "Munnar", "Muvattupuzha", "Nedumangad", "Neyyattinkara", "Nilambur", "Nileshwaram",
    "North Paravur", "Ottapalam", "Pala", "Palakkad", "Paravur", "Pathanamthitta", "Pathanapuram", "Payyanur",
    "Peerumade", "Perinthalmanna", "Perumbavoor", "Ponnani", "Punalur", "Ramanattukara", "Ranni", "Shoranur",
    "Sulthan Bathery", "Taliparamba", "Thalassery", "Thiruvalla", "Thiruvananthapuram", "Thodupuzha", "Thrikkakara", "Thrissur",
    "Tirur", "Tripunithura", "Vaikom", "Varkala", "Vatakara", "Vypin", "Wayanad"
  ],
  "Ladakh": [
    "Alchi", "Basgo", "Batalik", "Bodh Kharbu", "Bogdang", "Changthang", "Charasa", "Chiktan",
    "Choglamsar", "Chulichan", "Chumathang", "Chushul", "Diskit", "Drass", "Durbuk", "Garkone",
    "Hanle", "Hemis", "Hunder", "Kargil", "Karu", "Khaltsi", "Khardung", "Kharmang",
    "Kyagar", "Lamayuru", "Leh", "Likir", "Mulbekh", "Nimmu", "Nubra", "Nyoma",
    "Padum", "Panamik", "Pangong", "Panikhar", "Parkachik", "Partapur", "Rangdum", "Sankoo",
    "Saspol", "Saspul", "Shakar", "Shargole", "Shey", "Skurbuchan", "Spituk", "Stok",
    "Sumur", "Taisuru", "Tangtse", "Tegar", "Temisgam", "Thiksey", "Tingmosgang", "Trespone",
    "Turtuk", "Upshi", "Wakha", "Wanla", "Zanskar"
  ],
  "Lakshadweep": [
    "Agatti", "Amini", "Andrott", "Bangaram", "Bitra", "Byramgore", "Cherbaniani", "Cheriyam",
    "Chetlat", "Elikalpeni", "Kadmat", "Kalpeni", "Kavaratti", "Kiltan", "Minicoy", "Parali",
    "Perumal Par", "Pitti", "Suheli", "Thinnakara", "Tinnakara", "Valiyakara", "Viringili"
  ],
  "Madhya Pradesh": [
    "Agar Malwa", "Alirajpur", "Amarpatan", "Anuppur", "Ashoknagar", "Babai", "Bada Malhera", "Baihar",
    "Balaghat", "Baldeogarh", "Banda", "Bankhedi", "Bareli", "Barghat", "Barwaha", "Barwani",
    "Begamganj", "Beohari", "Betul", "Bhind", "Bhopal", "Bichhiya", "Bijadandi", "Bijawar",
    "Bina", "Birsinghpur", "Budni", "Burhanpur", "Buxwaha", "Chanderi", "Chhapara", "Chhatarpur",
    "Chhindwara", "Chitrangi", "Churhat", "Damoh", "Datia", "Deori", "Deosar", "Dewas",
    "Dhar", "Dindori", "Gadarwara", "Garhakota", "Garoth", "Gaurihar", "Ghansor", "Ghuwara",
    "Goharganj", "Gopadbanas", "Gotegaon", "Guna", "Gurh", "Gwalior", "Hanumana", "Harda",
    "Hoshangabad", "Indore", "Isagarh", "Itarsi", "Jabalpur", "Jaisinghnagar", "Jaithari", "Jatara",
    "Jawad", "Jhabua", "Kareli", "Kasrawad", "Katangi", "Katni", "Keolari", "Khandwa",
    "Khargone", "Khurai", "Kotar", "Kotma", "Kurwai", "Lakhnadon", "Lanji", "Lateri",
    "Laundi", "Lidhora", "Maheshwar", "Maihar", "Majhauli", "Malhargarh", "Manasa", "Mandla",
    "Mandleshwar", "Mandsaur", "Mangawan", "Mauganj", "Morena", "Mungaoli", "Murwara", "Nagod",
    "Nainpur", "Narayanganj", "Narmadapuram", "Narsinghpur", "Nasrullaganj", "Neemuch", "Niwari", "Niwas",
    "Nowgong", "Obedullaganj", "Orchha", "Palera", "Panna", "Paraswada", "Patharia", "Pipariya",
    "Pithampur", "Prithvipur", "Pushprajgarh", "Rahatgarh", "Raisen", "Rajgarh", "Rampur Baghelan", "Rampur Naikin",
    "Ratlam", "Rehli", "Rehti", "Rewa", "Sagar", "Sanawad", "Satna", "Sehore",
    "Semaria", "Sendhwa", "Seoni", "Seoni Malwa", "Shahdol", "Shahgarh", "Shajapur", "Sheopur",
    "Shivpuri", "Sidhi", "Silwani", "Singrauli", "Sironj", "Sitamau", "Sohagpur", "Susner",
    "Tendukheda", "Teonthar", "Tikamgarh", "Udaipura", "Ujjain", "Umaria", "Unchehara", "Vidisha",
    "Waraseoni"
  ],
  "Maharashtra": [
    "Achalpur", "Aheri", "Ahmadpur", "Ahmednagar", "Akkalkot", "Akola", "Akole", "Akot",
    "Alibag", "Amalner", "Ambad", "Ambajogai", "Ambegaon", "Amgaon", "Amravati", "Anjangaon",
    "Ardhapur", "Armori", "Arvi", "Ashti", "Aundh", "Aurangabad", "Ausa", "Badlapur",
    "Badnapur", "Baglan", "Balapur", "Ballarpur", "Baner", "Baramati", "Barshi", "Barshitakli",
    "Beed", "Bhandara", "Bhatkuli", "Bhiwandi", "Bhokar", "Bhokardan", "Bhor", "Bhum",
    "Bhusawal", "Biloli", "Chakan", "Chakur", "Chalisgaon", "Chamorshi", "Chandrapur", "Chandur Bazar",
    "Chandur Railway", "Chandwad", "Chikhaldara", "Chiplun", "Chopda", "Dapoli", "Daryapur", "Daund",
    "Degloor", "Deola", "Deoli", "Desaiganj", "Devrukh", "Dhamangaon", "Dharangaon", "Dharni",
    "Dharur", "Dhule", "Dindori", "Dodamarg", "Erandol", "Etapalli", "Faizpur", "Gadchiroli",
    "Gangapur", "Georai", "Ghansawangi", "Gondia", "Goregaon", "Guhagar", "Hadapsar", "Hadgaon",
    "Haveli", "Himayatnagar", "Hinganghat", "Hinjewadi", "Ichalkaranji", "Igatpuri", "Indapur", "Jafrabad",
    "Jalgaon", "Jalna", "Jamkhed", "Jamner", "Junnar", "Kaij", "Kalamb", "Kalwan",
    "Kalyan", "Kamptee", "Kandhar", "Kankavli", "Kannad", "Karanja", "Karanja Lad", "Karjat",
    "Karmala", "Khalapur", "Kharadi", "Khed", "Khultabad", "Kinwat", "Kolhapur", "Kopargaon",
    "Kothrud", "Kudal", "Kurduwadi", "Kurkheda", "Lakhani", "Lanja", "Latur", "Loha",
    "Lonavala", "Madha", "Mahad", "Mahur", "Majalgaon", "Malegaon", "Malshiras", "Malvan",
    "Mandangad", "Mangalvedhe", "Mangaon", "Mangrulpir", "Manjlegaon", "Manmad", "Manora", "Mantha",
    "Maval", "Mhasla", "Mohadi", "Mohol", "Morshi", "Mudkhed", "Mukhed", "Mulchera",
    "Mulshi", "Mumbai", "Murtizapur", "Murud", "Nagpur", "Naigaon", "Nanded", "Nandgaon",
    "Nandgaon Khandeshwar", "Nashik", "Navi Mumbai", "Newasa", "Nilanga", "Niphad", "Osmanabad", "Pachora",
    "Paithan", "Pandharpur", "Panvel", "Paranda", "Parbhani", "Parner", "Parola", "Partur",
    "Pathardi", "Patoda", "Patur", "Pauni", "Pen", "Peth", "Phulambri", "Pimpri-Chinchwad",
    "Poladpur", "Pulgaon", "Pune", "Purandar", "Rahuri", "Rajapur", "Ratnagiri", "Raver",
    "Risod", "Roha", "Sadak Arjuni", "Sakoli", "Salekasa", "Samudrapur", "Sangameshwar", "Sangamner",
    "Sangola", "Satana", "Satara", "Savda", "Sawantwadi", "Seloo", "Shevgaon", "Shirdi",
    "Shirur", "Shirur Anantpal", "Shirur Kasar", "Shivajinagar", "Shrirampur", "Shrivardhan", "Sillod", "Sindhudurg",
    "Sinnar", "Sironcha", "Solapur", "Soygaon", "Surgana", "Tala", "Talegaon", "Telhara",
    "Teosa", "Thane", "Tirora", "Trimbak", "Tuljapur", "Tumsar", "Udgir", "Ulhasnagar",
    "Umarga", "Uran", "Vaibhavwadi", "Vaijapur", "Vasai", "Velhe", "Vengurla", "Viman Nagar",
    "Virar", "Wadwani", "Wagholi", "Wakad", "Wardha", "Warud", "Washi", "Washim",
    "Yavatmal", "Yawal", "Yeola"
  ],
  "Manipur": [
    "Andro", "Bishnupur", "Chakpikarong", "Chandel", "Chingai", "Churachandpur", "Heirok", "Hundung",
    "Imphal", "Jessami", "Jiribam", "Kakching", "Kakching Khunou", "Kamjong", "Kanglatongbi", "Kangpokpi",
    "Kasom Khullen", "Khongjom", "Khoupum", "Kwatha", "Lambui", "Lamlai", "Lilong", "Lilong Chajing",
    "Longmai", "Machi", "Mao", "Maram", "Mayang Imphal", "Moirang", "Moreh", "Nambol",
    "Ningthoukhong", "Noney", "Nungba", "Oinam", "Pallel", "Pherzawl", "Phungyar", "Purul",
    "Saikul", "Saitu", "Samurou", "Sekmai", "Senapati", "Shangshak", "Somdal", "Sugnu",
    "Tadubi", "Tamei", "Tamenglong", "Tengnoupal", "Thoubal", "Tousem", "Ukhrul", "Wabagai",
    "Wangjing", "Wangoi", "Wilong", "Yairipok"
  ],
  "Meghalaya": [
    "Adokgre", "Amlarem", "Ampati", "Baghmara", "Bajengdoba", "Betasing", "Byrnihat", "Cherrapunji",
    "Chokpot", "Dadenggre", "Dalu", "Dawki", "Gambegre", "Gasuapara", "Jowai", "Kharkutta",
    "Khliehriat", "Laban", "Laitumkhrah", "Laskein", "Lumshnong", "Mahendraganj", "Mairang", "Mawkyrwat",
    "Mawlai", "Mawphlang", "Mawshynrut", "Mawsynram", "Mendipathar", "Nongkhlaw", "Nongpoh", "Nongspung",
    "Nongstoin", "Nongthymmai", "Phulbari", "Police Bazar", "Pynursla", "Rambrai", "Ranikor", "Resubelpara",
    "Rongara", "Rongjeng", "Rongram", "Saipung", "Samanda", "Selsella", "Shella", "Shillong",
    "Siju", "Smit", "Sohra", "Songsak", "Sutnga", "Thadlaskein", "Tikrikilla", "Tura",
    "Umiam", "Umroi", "Williamnagar", "Zikzak"
  ],
  "Mizoram": [
    "Aizawl", "Bairabi", "Biate", "Bilkhawthlir", "Bualpui", "Buarpui", "Champhai", "Chawngte",
    "Darlawn", "Diltlang", "East Lungdar", "Farkawn", "Hnahthial", "Kawnpui", "Keifang", "Khawbung",
    "Khawzawl", "Kolasib", "Lawngtlai", "Lunglei", "Mamit", "Ngengpui", "Ngopa", "North Vanlaiphai",
    "Palak", "Pangzawl", "Phuaibuang", "Phullen", "Phura", "Reiek", "Saiha", "Saitual",
    "Sangau", "Serchhip", "Tawipui", "Thenzawl", "Thingdawl", "Thingsul", "Thingsulthliah", "Tipa",
    "Tlabung", "Tlangnuam", "Tuipang", "Vairengte", "Vaphai", "West Phaileng", "Zawlnuam", "Zawlpui"
  ],
  "Nagaland": [
    "Aboi", "Aghunato", "Ahthibung", "Akuluto", "Alongtaki", "Aquqhnaqua", "Atoizu", "Bhandari",
    "Changtongya", "Chen", "Chessore", "Chetheba", "Chizami", "Chozuba", "Chuchuyimlang", "Chumukedima",
    "Dhansiripar", "Dimapur", "Jalukie", "Kiphire", "Kobulong", "Kohima", "Kuhuboto", "Longchem",
    "Longkhim", "Longleng", "Longmatra", "Lotsu", "Mangkolemba", "Medziphema", "Meluri", "Mhainamtsi",
    "Mokokchung", "Mon", "Ngwalwa", "Niuland", "Noklak", "Noksen", "Ongpangkong", "Panso",
    "Peren", "Pfutsero", "Phek", "Phomching", "Pungro", "Ralan", "Sakshi", "Sanis",
    "Satakha", "Sekruzu", "Seyochung", "Shamator", "Sitimi", "Suruhuto", "Tamlu", "Tening",
    "Thonoknyu", "Tizit", "Tobu", "Tseminyu", "Tuensang", "Tuli", "Wokha", "Yongnyah",
    "Zunheboto"
  ],
  "Odisha": [
    "Anandapur", "Angul", "Astaranga", "Athagarh", "Athmalik", "Athmallik", "Aul", "Badamba",
    "Balangir", "Balasore", "Balianta", "Balikuda", "Balipatna", "Bamra", "Banapur", "Banarpal",
    "Banei", "Banki", "Baramba", "Barbil", "Bargarh", "Bari", "Baripada", "Barkote",
    "Begunia", "Belpahar", "Berhampur", "Bhadrak", "Bhapur", "Bhawanipatna", "Bhuban", "Bhubaneswar",
    "Binjharpur", "Biramitrapur", "Biridi", "Bisra", "Boinda", "Bolagarh", "Bonai", "Boudh",
    "Brahmagiri", "Brajarajnagar", "Champua", "Chandikhol", "Chhendipada", "Chilika", "Choudwar", "Cuttack",
    "Danagadi", "Dasarathpur", "Daspalla", "Debagarh", "Delanga", "Derabish", "Dharmasala", "Dhenkanal",
    "Ersama", "Gajapati", "Gania", "Ganjam", "Garadpur", "Ghasipura", "Ghatgaon", "Gondia",
    "Gop", "Harichandanpur", "Hatadihi", "Hemgir", "Hindol", "Jagatsinghpur", "Jajpur", "Jatni",
    "Jeypore", "Jharsuguda", "Joda", "Kakatpur", "Kalahandi", "Kamakhyanagar", "Kanas", "Kandhamal",
    "Kaniha", "Kankadahad", "Kantabanji", "Kantapada", "Kendrapara", "Keonjhar", "Khandapada", "Khordha",
    "Kishorenagar", "Koira", "Konark", "Koraput", "Korei", "Krushnaprasad", "Kuakhia", "Kuchinda",
    "Kujang", "Kutra", "Lahunipara", "Lephripara", "Loisinga", "Mahakalapada", "Mahanga", "Malkangiri",
    "Marshaghai", "Mayurbhanj", "Motunga", "Nabarangpur", "Nalco Nagar", "Narsinghpur", "Naugaon", "Nayagarh",
    "Niali", "Nimapara", "Nischintakoili", "Nuagaon", "Nuapada", "Odagaon", "Odapada", "Pallahara",
    "Panposh", "Paradip", "Parjang", "Patnagarh", "Pattamundai", "Phulbani", "Pipili", "Puri",
    "Purunakot", "Raghunathpur", "Rairakhol", "Rajgangpur", "Rajnagar", "Ranapur", "Rasulpur", "Rayagada",
    "Reamal", "Redhakhol", "Rourkela", "Saharpada", "Salipur", "Sambalpur", "Satyabadi", "Subarnapur",
    "Sukinda", "Sundargarh", "Talcher", "Tangarpali", "Tangi", "Telkoi", "Tigiria", "Tileibani",
    "Tirtol", "Titilagarh", "Tushra", "Vyasanagar"
  ],
  "Puducherry": [
    "Adi Andhrapeta", "Ariyankuppam", "Auroville", "Bahour", "Beach Road", "Bommayarpalayam", "Chalakara", "Chunnambar",
    "Dariyalatippa", "Embalam", "Farampeta", "French Colony", "Gorimedu", "Goubert Avenue", "Guerempeta", "Indira Nagar",
    "Jipmer", "Kalapet", "Kamaraj Nagar", "Kanakalapeta", "Karaikal", "Karikalampakkam", "Katterikuppam", "Kirumampakkam",
    "Korkadu", "Kottucherry", "Lawspet", "Madagadipet", "Mahe", "Mannadipet", "Mudaliarpet", "Muthialpet",
    "Nainarmandapam", "Neravy", "Nettapakkam", "Oulgaret", "Palloor", "Pandakkal", "Paradise Beach", "Pillaichavady",
    "Promenade", "Puducherry", "Raj Bhavan", "Reddiyarpalayam", "Saram", "Serenity Beach", "Sorapet", "T.R. Pattinam",
    "Thirubuvanai", "Thirukkanur", "Thirunallar", "Villianur", "White Town", "Yanam"
  ],
  "Punjab": [
    "Abohar", "Adampur", "Ahmedgarh", "Ajnala", "Amargarh", "Amritsar", "Anandpur Sahib", "Attari",
    "Balachaur", "Balluana", "Banga", "Banur", "Bareta", "Bariwala", "Barnala", "Bassian",
    "Batala", "Bathinda", "Beas", "Bhadaur", "Bhawanigarh", "Bhikhi", "Bhikhiwind", "Bhogpur",
    "Bhucho Mandi", "Budhlada", "Chamkaur Sahib", "Chohla Sahib", "Dasuya", "Derabassi", "Dhanaula", "Dhariwal",
    "Dhuri", "Dinanagar", "Dirba", "Doraha", "Faridkot", "Fatehgarh Churian", "Fazilka", "Firozpur",
    "Garhdiwala", "Garhshankar", "Gidderbaha", "Goindwal", "Goniana", "Goraya", "Gurdaspur", "Guru Har Sahai",
    "Handiaya", "Hariana", "Hoshiarpur", "Jagraon", "Jaitu", "Jalalabad", "Jalandhar", "Jandiala Guru",
    "Jhunir", "Kalanaur", "Kapurthala", "Kartarpur", "Khadoor Sahib", "Khanna", "Kharar", "Khemkaran",
    "Kotkapura", "Kurali", "Lehragaga", "Longowal", "Ludhiana", "Machhiwara", "Mahilpur", "Majitha",
    "Makhu", "Malerkotla", "Malout", "Mansa", "Maur", "Mehal Kalan", "Moga", "Mohali",
    "Morinda", "Mukerian", "Muktsar", "Nabha", "Nakodar", "Nangal", "Naushehra Pannuan", "Nawanshahr",
    "Nurmahal", "Pathankot", "Patiala", "Patti", "Payal", "Phagwara", "Phillaur", "Phul",
    "Qadian", "Raikot", "Rajpura", "Raman", "Rampura Phul", "Rayya", "Ropar", "Sahnewal",
    "Samana", "Samrala", "Sangat", "Sangrur", "Sardulgarh", "Shahkot", "Sirhind", "Sri Hargobindpur",
    "Sunam", "Talwandi Sabo", "Talwara", "Tanda", "Tapa", "Tarn Taran", "Zira", "Zirakpur"
  ],
  "Rajasthan": [
    "Abu Road", "Ahore", "Ajmer", "Aklera", "Alwar", "Amber", "Amet", "Anandpuri",
    "Anta", "Anupgarh", "Asind", "Asnawar", "Aspur", "Atru", "Bagidora", "Bakani",
    "Bali", "Balotra", "Bandikui", "Banera", "Banswara", "Baran", "Bari Sadri", "Barmer",
    "Bassi", "Baswa", "Bayana", "Baytu", "Beawar", "Begun", "Behror", "Bhadesar",
    "Bhadra", "Bharatpur", "Bhilwara", "Bhim", "Bhinai", "Bhinmal", "Bhiwadi", "Bhusawar",
    "Bichhiwara", "Bidasar", "Bikaner", "Chaksu", "Chechat", "Chhabra", "Chhipabarod", "Chittorgarh",
    "Chohtan", "Chomu", "Churu", "Danta Ramgarh", "Dausa", "Deeg", "Degana", "Deogarh",
    "Deoli", "Desuri", "Didwana", "Diggi", "Digod", "Dudu", "Dungargarh", "Dungarpur",
    "Dungla", "Ellenabad", "Falna", "Fatehgarh", "Fatehnagar", "Fatehpur", "Gajsinghpur", "Gangrar",
    "Garhi", "Ghatol", "Gogunda", "Gudamalani", "Hanumangarh", "Hurda", "Jahazpur", "Jaipur",
    "Jaisalmer", "Jaitaran", "Jalore", "Jamwa Ramgarh", "Jayal", "Jhadol", "Jhalawar", "Jhunjhunu",
    "Jobner", "Jodhpur", "Kaman", "Kankroli", "Kanwas", "Kapasan", "Karanpur", "Kathumar",
    "Kekri", "Kelwa", "Khairthal", "Khajuwala", "Khandela", "Khanpur", "Kishanganj", "Kishangarh",
    "Kishangarh Bas", "Kolayat", "Kota", "Kotkasim", "Kotputli", "Kotra", "Kotri", "Kuchaman",
    "Kuchaman City", "Kumbhalgarh", "Kumher", "Kushalgarh", "Ladnun", "Ladpura", "Lalsot", "Lasadiya",
    "Laxmangarh", "Lunkaransar", "Mahwa", "Makrana", "Malpura", "Mandal", "Mandalgarh", "Mangrol",
    "Manohar Thana", "Marwar Junction", "Masuda", "Mauzamabad", "Mavli", "Merta", "Merta City", "Mount Abu",
    "Mundawar", "Mundwa", "Nadbai", "Nagar", "Nagaur", "Nangal", "Nasirabad", "Nathdwara",
    "Nawa", "Neem Ka Thana", "Neemrana", "Nimbahera", "Niwai", "Nohar", "Nokha", "Padampur",
    "Pahari", "Pali", "Parbatsar", "Peeplu", "Peesangan", "Phagi", "Phulera", "Pidawa",
    "Pilibanga", "Pindwara", "Pipalda", "Piprali", "Pirawa", "Pokaran", "Poogal", "Pushkar",
    "Railmagra", "Raipur", "Raisinghnagar", "Rajaldesar", "Rajgarh", "Rajsamand", "Ramganj Mandi", "Ramgarh",
    "Rani", "Raniwara", "Rashmi", "Ratangarh", "Ratannagar", "Rawatbhata", "Rawatsar", "Rawla Mandi",
    "Reengus", "Reodar", "Rohat", "Rupangarh", "Rupbas", "Sadulshahar", "Sagwara", "Sahara",
    "Salasar", "Salumber", "Sambhar", "Sanchore", "Sanganer", "Sangaria", "Sangod", "Sarada",
    "Sardarshahar", "Sarwar", "Sayla", "Shahabad", "Shahpura", "Sheo", "Sheoganj", "Sikar",
    "Sikrai", "Simalwara", "Sirohi", "Siwana", "Sojat", "Sri Ganganagar", "Sri Madhopur", "Sujangarh",
    "Sumerpur", "Suratgarh", "Takhatgarh", "Taranagar", "Thanagazi", "Tijara", "Todaraisingh", "Tonk",
    "Udaipur", "Uniara", "Vallabhnagar", "Vijaynagar", "Viratnagar", "Weir"
  ],
  "Sikkim": [
    "Burtuk", "Chungthang", "Damthang", "Dentam", "Deorali", "Dikchu", "Dzongu", "Gangtok",
    "Geyzing", "Gyalshing", "Hee Bermiok", "Jorethang", "Kaluk", "Katao", "Kewzing", "Khamdong",
    "Lachen", "Lachung", "Legship", "Lingdok", "Majitar", "Mangan", "Martam", "Melli",
    "Naga", "Namchi", "Namthang", "Naya Bazar", "Pakyong", "Passingdang", "Pelling", "Penlong",
    "Phodong", "Rakdong", "Rangpo", "Ranipool", "Ravangla", "Ravongla", "Reshi", "Rhenock",
    "Rongli", "Rumtek", "Samdur", "Sang", "Singhik", "Singtam", "Sombaria", "Soreng",
    "Tadong", "Tashiding", "Tathangchen", "Temi", "Thangu", "Tingda", "Toong", "Tumin",
    "Yangang", "Yuksom", "Yumthang"
  ],
  "Tamil Nadu": [
    "Adyar", "Agasteeswaram", "Alanganallur", "Alangayam", "Alangudi", "Alangulam", "Alathur", "Ambasamudram",
    "Ambattur", "Ambur", "Anchetti", "Andimadam", "Andipatti", "Anna Nagar", "Annur", "Anthiyur",
    "Arakkonam", "Arani", "Aranthangi", "Aravakurichi", "Arcot", "Ariyalur", "Aruppukkottai", "Athoor",
    "Attur", "Avadi", "Avinashi", "Avudaiyarkoil", "Bargur", "Batlagundu", "Bhavani", "Bhuvanagiri",
    "Bodinayakanur", "Boothapandi", "Budalur", "Chengalpattu", "Chengam", "Chennai", "Chetpet", "Cheyyur",
    "Chidambaram", "Chinnamanur", "Chinnasalem", "Chromepet", "Coimbatore", "Colachel", "Coonoor", "Cuddalore",
    "Cumbum", "Denkanikottai", "Devakottai", "Dharapuram", "Dharmapuri", "Dindigul", "Edappadi", "Egmore",
    "Erode", "Ettayapuram", "Gandarvakottai", "Gangavalli", "Gingee", "Gobichettipalayam", "Gudalur", "Gudiyatham",
    "Guduvancheri", "Guindy", "Harur", "Hosur", "Ilaiyankudi", "Iluppur", "Jayankondam", "Jolarpettai",
    "Kadavur", "Kadayampatti", "Kadayanallur", "Kalaiyarkoil", "Kalasapakkam", "Kallakurichi", "Kanchipuram", "Kangeyam",
    "Kanyakumari", "Karaikkudi", "Karambakudi", "Kariapatti", "Karimangalam", "Karur", "Katpadi", "Kattumannarkoil",
    "Kayathar", "Kelambakkam", "Killiyoor", "Kilvelur", "Kinathukadavu", "Kodaikanal", "Kodambakkam", "Kodavasal",
    "Kodumudi", "Kolli Hills", "Kotagiri", "Kovilpatti", "Krishnagiri", "Krishnarayapuram", "Kulithalai", "Kumarapalayam",
    "Kumbakonam", "Kundah", "Kunnam", "Kurinjipadi", "Kuthalam", "Kuzhithurai", "Madathukulam", "Madhavaram",
    "Madukkarai", "Madurai", "Madurantakam", "Mahabalipuram", "Manamadurai", "Manamelkudi", "Mannargudi", "Maraimalai Nagar",
    "Marakkanam", "Mayiladuthurai", "Melur", "Mettupalayam", "Mettur", "Modakurichi", "Mohanur", "Muthupettai",
    "Mylapore", "Nagapattinam", "Nagercoil", "Namakkal", "Nanguneri", "Nannilam", "Natham", "Needamangalam",
    "Neyveli", "Nilakkottai", "Nungambakkam", "Oddanchatram", "Omalur", "Ooty", "Oragadam", "Orathanadu",
    "Ottapidaram", "Padmanabhapuram", "Palacode", "Palani", "Palayamkottai", "Palladam", "Pallavaram", "Pandalur",
    "Panruti", "Papanasam", "Pappireddipatti", "Paramakudi", "Paramathi Velur", "Pattukkottai", "Pennagaram", "Peraiyur",
    "Perambalur", "Periyakulam", "Perundurai", "Perur", "Pochampalli", "Pollachi", "Polur", "Poonamallee",
    "Porur", "Pudukkottai", "Pugalur", "Radhapuram", "Rajakkamangalam", "Rajapalayam", "Ranipet", "Rasipuram",
    "Red Hills", "Royapuram", "Salem", "Sankagiri", "Sankarankovil", "Sankarapuram", "Sathyamangalam", "Sattur",
    "Sendamangalam", "Sendurai", "Shenkottai", "Sholavandan", "Sholinghur", "Shoolagiri", "Singampunari", "Sirkazhi",
    "Sivaganga", "Sivakasi", "Srimushnam", "Sriperumbudur", "Srivaikuntam", "Srivilliputhur", "Sulur", "T Nagar",
    "Tambaram", "Tenkasi", "Thandrampet", "Thanjavur", "Tharangambadi", "Theni", "Thirumangalam", "Thirumayam",
    "Thiruthuraipoondi", "Thiruvaiyaru", "Thiruvidaimarudur", "Thisayanvilai", "Thoothukudi", "Thovalai", "Thuckalay", "Tindivanam",
    "Tiruchendur", "Tiruchengode", "Tiruchirappalli", "Tiruchuli", "Tirukalukundram", "Tirukoilur", "Tirunelveli", "Tirupathur",
    "Tiruppur", "Tiruvannamalai", "Tiruvarur", "Tondiarpet", "Triplicane", "Udayarpalayam", "Udhagamandalam", "Udumalaipettai",
    "Ulundurpet", "Usilampatti", "Uthamapalayam", "Uthangarai", "Vadipatti", "Valangaiman", "Valparai", "Vaniyambadi",
    "Vanur", "Vasudevanallur", "Vedaranyam", "Vedasandur", "Velachery", "Vellore", "Vembakottai", "Veppanthattai",
    "Vilathikulam", "Viluppuram", "Virudhachalam", "Virudhunagar", "Walajabad", "Wallajah", "Watrap", "Yercaud"
  ],
  "Telangana": [
    "Achampet", "Adilabad", "Alampur", "Alwal", "Amangal", "Ameerpet", "Andole", "Asifabad",
    "Aswaraopeta", "Banjara Hills", "Begumpet", "Bejjanki", "Bellampalli", "Bhadrachalam", "Bhadradri Kothagudem", "Bhainsa",
    "Boath", "Boinpalli", "Burgampahad", "Chandur", "Charla", "Chennaraopet", "Chennur", "Cherial",
    "Chevella", "Chityal", "Choppadandi", "Devarakonda", "Dharmapuri", "Dharur", "Dilawarpur", "Doultabad",
    "Dubbak", "Duggondi", "Dummugudem", "Eturnagaram", "Farooqnagar", "Gachibowli", "Gadwal", "Gajwel",
    "Gangadhara", "Geesugonda", "Ghanpur", "Ghatkesar", "Ghattu", "Godavarikhani", "Govindaraopet", "Hanamkonda",
    "Hayathnagar", "Hitech City", "Husnabad", "Huzurabad", "Huzurnagar", "Hyderabad", "Ibrahimpatnam", "Ieeja",
    "Indervelly", "Isnapur", "Itikyala", "Jadcherla", "Jagtial", "Jainoor", "Jaipur", "Jangaon",
    "Jayashankar Bhupalpally", "Jogipet", "Jogulamba Gadwal", "Jubilee Hills", "Kagaznagar", "Kalwakurthy", "Kamanpur", "Kamareddy",
    "Karimnagar", "Kazipet", "Keesara", "Kerameri", "Khammam", "Khanapur", "Kodad", "Kodangal",
    "Kollapur", "Kompally", "Konaraopet", "Kondapur", "Korutla", "Kosgi", "Kothagudem", "Kukatpally",
    "Laxmanchanda", "LB Nagar", "Lingala Ghanpur", "Luxettipet", "Maddur", "Madhapur", "Mahbubnagar", "Maheshwaram",
    "Makthal", "Malkajgiri", "Mallapur", "Manakondur", "Mancherial", "Mandamarri", "Mangapet", "Manopad",
    "Manthani", "Manuguru", "Medak", "Medchal", "Metpally", "Miryalaguda", "Miyapur", "Mudhole",
    "Mulugu", "Munugode", "Nagarkurnool", "Nakrekal", "Nalgonda", "Nampally", "Narayankhed", "Narayanpet",
    "Narnoor", "Narsampet", "Narsapur", "Nekkonda", "Neredigonda", "Nidamanur", "Nirmal", "Nizamabad",
    "Palakurthi", "Palwancha", "Pargi", "Parkal", "Patancheru", "Peddapalli", "Peddavoora", "Quthbullapur",
    "Raghunathpalle", "Raikal", "Rajanna Sircilla", "Ramagiri", "Ramagundam", "Rangareddy", "Sadasivpet", "Sangareddy",
    "Sangem", "Secunderabad", "Shadnagar", "Shamirpet", "Siddipet", "Sircilla", "Sirpur", "Station Ghanpur",
    "Sultanabad", "Suryapet", "Tadvai", "Tandur", "Telkapalle", "Thipparthi", "Thoguta", "Timmapur",
    "Uppal", "Utkoor", "Utnoor", "Vemulawada", "Venkatapuram", "Vikarabad", "Waddepalle", "Wanaparthy",
    "Wankdi", "Warangal", "Wardhannapet", "Wazeed", "Yadadri Bhuvanagiri", "Yellandu", "Yellareddipet", "Zahirabad"
  ],
  "Tripura": [
    "Agartala", "Amarpur", "Ambassa", "Ampi", "Baikhora", "Bakafa", "Belonia", "Bishalgarh",
    "Boxanagar", "Chawmanu", "Chebri", "Damcherra", "Dasda", "Dharmanagar", "Dumburnagar", "Durga Chowmuhani",
    "Fatikroy", "Ganganagar", "Gournagar", "Hezamara", "Hrishyamukh", "Jampui Hills", "Jampuijala", "Jirania",
    "Jolaibari", "Jubarajnagar", "Kailashahar", "Kakraban", "Kalyanpur", "Kamalpur", "Kanchanpur", "Karbook",
    "Kathalia", "Khowai", "Killa", "Kumarghat", "Laljuri", "Lefunga", "Longtharai Valley", "Mandai",
    "Manu", "Matarbari", "Melaghar", "Mohanpur", "Muhuripur", "Mungiakami", "Nalchar", "Ompi",
    "Padmabil", "Panisagar", "Pecharthal", "Rajnagar", "Ranirbazar", "Rupaichari", "Sabroom", "Salema",
    "Santirbazar", "Satchand", "Sepahijala", "Silachari", "Sonamura", "Takurjala", "Teliamura", "Tepania",
    "Tulashikhar", "Udaipur", "Vangmun"
  ],
  "Uttar Pradesh": [
    "Afzalgarh", "Agra", "Ahraura", "Airayan", "Akbarpur", "Aligarh", "Allganj", "Amethi",
    "Amroha", "Anandnagar", "Aonla", "Arajiline", "Atarra", "Aurai", "Auras", "Awagarh",
    "Ayah", "Ayodhya", "Azamgarh", "Baberu", "Babina", "Bachhrawan", "Bahadurpur", "Baheri",
    "Bahjoi", "Bahraich", "Bahua", "Bairia", "Bakshi Ka Talab", "Baldirai", "Ballia", "Balrampur",
    "Banda", "Bangarmau", "Bansdih", "Bansgaon", "Bansi", "Bar", "Barabanki", "Baragaon",
    "Bareilly", "Barhaj", "Barkhera", "Basti", "Belthara Road", "Bhadohi", "Bhatpar Rani", "Bhinga",
    "Bhognipur", "Bighapur", "Bijnor", "Bijpur", "Bikapur", "Bilari", "Bilaspur", "Bilhaur",
    "Binawar", "Bindki", "Birdha", "Birdpur", "Bisalpur", "Bisauli", "Bithoor", "Budaun",
    "Bulandshahr", "Burhanpur", "Campierganj", "Captanganj", "Chandausi", "Chandpur", "Charkhari", "Chatra",
    "Chaubepur", "Chauri Chaura", "Chinhat", "Chiraigaon", "Chirgaon", "Cholapur", "Chopan", "Chunar",
    "Churk", "Colonelganj", "Dalmau", "Dariyabad", "Dataganj", "Deoria", "Derapur", "Dewa",
    "Dhampur", "Dhanghata", "Dhata", "Dohrighat", "Domariyaganj", "Dostpur", "Dubhar", "Dudhi",
    "Erich", "Etah", "Etawah", "Faizabad", "Faridpur", "Farrukhabad", "Fatehpur", "Fatehpur Chaurasi",
    "Fazilnagar", "Firozabad", "Gainsari", "Garautha", "Gauriganj", "Ghanghata", "Ghatampur", "Ghaziabad",
    "Ghazipur", "Ghorawal", "Ghosi", "Gilaula", "Gohand", "Gola", "Gonda", "Gopiganj",
    "Gorakhpur", "Gosainganj", "Greater Noida", "Gunnaur", "Gursarai", "Gyanpur", "Haidergarh", "Haldaur",
    "Hallia", "Hamirpur", "Hapur", "Harchandpur", "Hardoi", "Harhua", "Harraiya", "Hasanganj",
    "Haswa", "Hata", "Hathras", "Ikauna", "Itaunja", "Itiathok", "Itwa", "Jagatpur",
    "Jagdishpur", "Jahanabad", "Jaisinghpur", "Jakhania", "Jakhaura", "Jalaun", "Jamunaha", "Jaunpur",
    "Jhansi", "Jhinjhak", "Kabrai", "Kadipur", "Kaiserganj", "Kakori", "Kakrala", "Kalpi",
    "Kanpur", "Kanpur Dehat", "Kanth", "Kaptanganj", "Karanda", "Kasaya", "Kasganj", "Kasimabad",
    "Katra", "Katra Bazar", "Kauriram", "Khadda", "Khaga", "Khajni", "Khalilabad", "Khesraha",
    "Khurja", "Kiratpur", "Koilsa", "Konch", "Kopaganj", "Kulpahar", "Kunda", "Kushinagar",
    "Kuthond", "Lakhimpur", "Lalganj", "Lalitpur", "Lambhua", "Lar", "Lucknow", "Madawara",
    "Madhogarh", "Madhuban", "Maharajganj", "Mahasi", "Mahoba", "Mahroni", "Mainpuri", "Malihabad",
    "Mandhata", "Maniyar", "Mankapur", "Marihan", "Martinganj", "Masodha", "Mathura", "Mau",
    "Maudaha", "Maunath Bhanjan", "Mauranipur", "Meerganj", "Meerut", "Mehdawal", "Mehnagar", "Mihinpurwa",
    "Milkipur", "Mirzapur", "Miyanganj", "Modinagar", "Mohammadabad", "Mohanlalganj", "Moradabad", "Moth",
    "Muhammadabad", "Musafirkhana", "Muskara", "Muzaffarnagar", "Nagina", "Nagwa", "Najibabad", "Nanpara",
    "Naraini", "Nath Nagar", "Naugarh", "Nautanwa", "Nawabganj", "Nebua Naurangia", "Nehtaur", "Nichlaul",
    "Nizamabad", "Noida", "Noorpur", "Obra", "Orai", "Pachperwa", "Padrauna", "Pahari",
    "Pali", "Paniyara", "Panwari", "Pathardeva", "Patti", "Payagpur", "Pharenda", "Phulpur",
    "Pilibhit", "Pindra", "Pipraich", "Pratapgarh", "Prayagraj", "Pukhrayan", "Puranpur", "Pure Dalai",
    "Purwa", "Raebareli", "Rajgarh", "Ramnagar", "Rampur", "Rampur Karkhana", "Rampura", "Raniganj",
    "Ranipur", "Rasra", "Rasulabad", "Rath", "Rehra Bazar", "Renukoot", "Reoti", "Risia",
    "Robertsganj", "Rudauli", "Rudhauli", "Rudrapur", "Sadat", "Safipur", "Saharanpur", "Sahaspur",
    "Sahaswan", "Sahjanwa", "Saidpur", "Salempur", "Salon", "Saltaua Gopalpur", "Sambhal", "Samthar",
    "Sangipur", "Sant Kabir Nagar", "Sant Ravidas Nagar", "Sarila", "Seohara", "Seorahi", "Shahjahanpur", "Shamli",
    "Shekhupur", "Sherkot", "Shikohabad", "Shivrajpur", "Shohratgarh", "Shravasti", "Siddharthnagar", "Siddhaur",
    "Sikanderpur", "Sikandra", "Sirauli Gauspur", "Sirsiya", "Siswa", "Sitapur", "Sohawal", "Sonbhadra",
    "Srinagar", "Suar", "Sultanpur", "Sumerpur", "Suratganj", "Suriyawan", "Talbehat", "Tamkuhi Raj",
    "Tanda", "Tarabganj", "Tarun", "Tejwapur", "Thakurdwara", "Tiloi", "Tindwari", "Tulsipur",
    "Ujhani", "Umri", "Unchahar", "Unnao", "Usehat", "Utraula", "Varanasi", "Vindhyachal",
    "Wazirganj", "Zamania"
  ],
  "Uttarakhand": [
    "Almora", "Augustmuni", "Badrinath", "Bageshwar", "Baijnath", "Bajpur", "Banbasa", "Barakot",
    "Barkot", "Berinag", "Betalghat", "Bhagwanpur", "Bhatwari", "Bhikiyasain", "Bhimtal", "Bhowali",
    "Bironkhal", "Chakrata", "Chamba", "Chamoli", "Champawat", "Chaubattakhal", "Chaukhutiya", "Chinyalisaur",
    "Chopta", "Dehradun", "Devprayag", "Dharchula", "Dhari", "Dhumakot", "Didihat", "Dineshpur",
    "Doiwala", "Dunda", "Dwarahat", "Gadarpur", "Gairsain", "Gangolihat", "Garur", "Gopeshwar",
    "Guptkashi", "Haldwani", "Haridwar", "Herbertpur", "Jainti", "Jakhnidhar", "Jakholi", "Jaspur",
    "Joshimath", "Jwalapur", "Kaladhungi", "Kalsi", "Kanalichhina", "Kanda", "Kapkot", "Karnaprayag",
    "Kashipur", "Kathgodam", "Kedarnath", "Khatima", "Kirti Nagar", "Kotabagh", "Kotdwar", "Laksar",
    "Lalkuan", "Lamgara", "Landhaura", "Lansdowne", "Lohaghat", "Mahua Dabra", "Manglaur", "Mori",
    "Mukteshwar", "Munakot", "Muni Ki Reti", "Munsiyari", "Mussoorie", "Nainital", "Nanaksagar", "Nandprayag",
    "Narendranagar", "Naugaon", "New Tehri", "Okhalkanda", "Pati", "Pauri", "Pithoragarh", "Pokhari",
    "Pratapnagar", "Purnagiri", "Purola", "Raiwala", "Ramgarh", "Ramnagar", "Ranikhet", "Ranipur",
    "Rishikesh", "Roorkee", "Rudraprayag", "Rudrapur", "Sahaspur", "Satpuli", "Sidcul", "Sitarganj",
    "Someshwar", "Srinagar", "Swarg Ashram", "Syalde", "Tanakpur", "Tapovan", "Tehri", "Thalisain",
    "Tharali", "Thauldhar", "Ukhimath", "Uttarkashi", "Vikasnagar", "Yamkeshwar"
  ],
  "West Bengal": [
    "Adra", "Alipurduar", "Amta", "Andal", "Arambagh", "Asansol", "Ashoknagar", "Ausgram",
    "Baduria", "Bagdah", "Baghmundi", "Bagnan", "Baharampur", "Baidyabati", "Balagarh", "Balarampur",
    "Bally", "Balurghat", "Bamangola", "Banarhat", "Bandel", "Bangaon", "Bankura", "Bansihari",
    "Barabani", "Barabazar", "Baranagar", "Barasat", "Bardhaman", "Barjora", "Barrackpore", "Baruipur",
    "Basanti", "Basirhat", "Belur", "Bhadreswar", "Bhagabanpur", "Bhagwanpur", "Bhangar", "Bhatar",
    "Bhatpara", "Bidhannagar", "Birpara", "Bishnupur", "Bundwan", "Buniadpur", "Burnpur", "Canning",
    "Chakdaha", "Chakulia", "Champdani", "Chanchal", "Chandannagar", "Chandipur", "Chanditala", "Chandrakona",
    "Chhatna", "Chinsurah", "Chopra", "Contai", "Cooch Behar", "Dadpur", "Dalkhola", "Dankuni",
    "Darjeeling", "Debra", "Deshapran", "Dhaniakhali", "Dhulian", "Dhupguri", "Diamond Harbour", "Digha",
    "Dinhata", "Domjur", "Dum Dum", "Durgapur", "Egra", "English Bazar", "Falakata", "Falta",
    "Faridpur", "Gaighata", "Galsi", "Gangajalghati", "Gangarampur", "Garbeta", "Garhbeta", "Garulia",
    "Gazole", "Ghatal", "Ghoom", "Goalpokhar", "Goghat", "Gorubathan", "Gosaba", "Habibpur",
    "Habra", "Haldia", "Haldibari", "Halisahar", "Haripal", "Harirampur", "Harishchandrapur", "Haroa",
    "Hasimara", "Hasnabad", "Hemtabad", "Hili", "Hingalganj", "Hooghly", "Howrah", "Hura",
    "Ichapore", "Indpur", "Indus", "Islampur", "Itahar", "Jagatballavpur", "Jaigaon", "Jalpaiguri",
    "Jamalpur", "Jamuria", "Jangipara", "Jhalda", "Joynagar", "Kakdwip", "Kalchini", "Kaliachak",
    "Kaliaganj", "Kalimpong", "Kalna", "Kalyani", "Kamarhati", "Kanchrapara", "Karandighi", "Kashipur",
    "Katwa", "Keshiary", "Keshpur", "Khanakul", "Khandaghosh", "Kharagpur", "Khardaha", "Khatra",
    "Khejuri", "Kishanganj", "Kolaghat", "Kolkata", "Konnagar", "Kotulpur", "Krishnanagar", "Kulpi",
    "Kultali", "Kulti", "Kumarganj", "Kumargram", "Kurseong", "Kushmandi", "Lava", "Lebong",
    "Liluah", "Lolegaon", "Madarihat", "Madhyamgram", "Magrahat", "Mahishadal", "Malbazar", "Malda",
    "Manbazar", "Mandarmani", "Mandirbazar", "Manebhanjan", "Manikchak", "Mathabhanga", "Mathurapur", "Matiali",
    "Maynaguri", "Medinipur", "Mejia", "Mekhliganj", "Memari", "Minakhan", "Mirik", "Mogra",
    "Monteswar", "Moyna", "Nabadwip", "Nadanghat", "Nagrakata", "Naihati", "Namkhana", "Nandakumar",
    "Nandigram", "Narayangarh", "Neturia", "New Town", "Nituria", "Old Malda", "Onda", "Panchla",
    "Pandabeswar", "Pandua", "Panihati", "Panskura", "Para", "Patashpur", "Patharpratima", "Patrasayer",
    "Pedong", "Pingla", "Polba", "Puncha", "Purbasthali", "Pursurah", "Purulia", "Raghunathpur",
    "Raiganj", "Raina", "Raipur", "Rajarhat", "Ramnagar", "Ranaghat", "Raniganj", "Ratua",
    "Rimbick", "Rishra", "Sabang", "Sagar", "Salanpur", "Salboni", "Salkia", "Salt Lake",
    "Saltora", "Sandakphu", "Sandeshkhali", "Sankrail", "Santuri", "Sarenga", "Serampore", "Shantipur",
    "Shibpur", "Shyampur", "Siliguri", "Simlapal", "Singur", "Sonada", "Sonamukhi", "Sonarpur",
    "Sukna", "Sutahata", "Swarupnagar", "Taldangra", "Tamluk", "Tapan", "Tarakeswar", "Tindharia",
    "Titagarh", "Tufanganj", "Uluberia", "Uttarpara"
  ],
};

/** Ordered list of all Indian States and Union Territories. */
export const INDIA_STATES = Object.freeze(Object.keys(INDIA_LOCATIONS));

/** O(1) city lookup by state name. */
export const getCitiesForState = (state) => {
  if (!state) return [];
  return INDIA_LOCATIONS[state] || [];
};
